In [23]:
#Basic Import
#Import Necessary Library

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#Import wordcloud for text visualization
#!pip install WordCloud
from wordcloud import WordCloud

#import NLTK

import nltk 
from nltk.corpus import stopwords

#dowloading NLTK data
nltk.download("stopwords")

# download tokenizer data
nltk.download("punkt")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Amit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [24]:
df= pd.read_csv("E:\git-tutorial\MLOps-OOP\MLOps-Complete-Pipeline\Experiment\spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
#Data Preprocessing

from sklearn.preprocessing import LabelEncoder

Encoder= LabelEncoder()
df["Category"]= Encoder.fit_transform(df["Category"])
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [26]:
#Check duplicates
df.duplicated().sum()

415

In [27]:
#Remove Duplicate

df= df.drop_duplicates(keep='first')
df.count()

Category    5157
Message     5157
dtype: int64

In [28]:
#Feature Engineering

#import the porter stemmer for text stemming

from nltk.stem.porter import PorterStemmer

#Import the string module for handling the special character

import string

#create an instance of porter stemmer

ps= PorterStemmer()

In [32]:
#Lower case transformation and text preprocessing

def transform_text(text):
    #transform the text to lower case

    text= text.lower()

    #Tokenization using NLTK

    text=nltk.word_tokenize(text)

    #Removing special character

    y=[]
    for i in text:
        if i.isalnum():
            y.append(i)

    #Remove stop words and punctuation

    text= y[:]
    y.clear()

    #Loop through tokens and remove stop words

    for i in text:
        if i not in stopwords.words("english") and i not in string.punctuation:
            y.append(i)


    #Stemming using porter stemmer

    text= y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))

    # Join the process token back to the single string

    return " ".join(y)

In [33]:
transform_text("Go until jurong point, crazy...Available only in  bugis n great world is a buffet..")

'go jurong point crazi avail bugi n great world buffet'

In [35]:
df["transform_text"]= df["Message"].apply(transform_text)

In [36]:
df.head()

,Category,Message,transform_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [ ]:
#Feature Engineering
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

tfidf=  TfidfVectorizer(max_features=500)

In [39]:
x= tfidf.fit_transform(df["transform_text"]).toarray()
y= df["Category"].values

In [ ]:
#Train test spilit

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,text_size= 0.20, random_state=2)

In [40]:
#Model Training

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [42]:
!pip install xgboost

Collecting xgboost

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading xgboost-3.0.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\amit\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\amit\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.14.0)
Downloading xgboost-3.0.0-py3-none-win_amd64.whl (150.0 MB)
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
    --------------------------------------- 2.1/150.0 MB 22.4 MB/s eta 0:00:07
   - -------------------------------------- 7.2/150.0 MB 32.9 MB/s eta 0:00:05
   -- ------------------------------------- 9.9/150.0 MB 30.1 MB/s eta 0:00:05
   --- ------------------------------------ 11.4/150.0 MB 29.7 MB/s eta 0:00:05
   --- ------------------------------------ 12.8/150.0 MB 27.3 MB/s eta 0:00:06
   --- ------------------------------------ 13.3/150.0 MB 21.8 MB/s eta 0:00:07
   --- ------------------------------------ 13.6/150.0 MB 19.3 MB/s eta 0:00:08
   --- ------------------------------------ 13.8/150.0 MB 16.4 MB/s eta 0:00:09
   --- ------------------------------------ 14.0/150.0 MB 14.2 MB/s eta 0:00:10
   --- ------------------------------------ 14.2/150.0 MB 12.8 MB/s eta 0:00:11
   --- ------------------------------------ 14.4/150.0 MB 12.1 MB/s eta 0:00:12
   --- ------------------------------------ 14.5/150.0 MB 11.3 MB/s eta 0:00:12
   --- ------------------------------------ 14.8/150.0 MB 10.6 MB/s eta 0:00:13
   --- ------------------------------------ 15.0/150.0 MB 9.9 MB/s eta 0:00:14
   ---- ----------------------------------- 15.3/150.0 MB 9.2 MB/s eta 0:00:15
   ---- ----------------------------------- 15.6/150.0 MB 8.7 MB/s eta 0:00:16
   ---- ----------------------------------- 15.9/150.0 MB 8.2 MB/s eta 0:00:17
   ---- ----------------------------------- 16.3/150.0 MB 7.8 MB/s eta 0:00:18
   ---- ----------------------------------- 16.9/150.0 MB 7.4 MB/s eta 0:00:19
   ---- ----------------------------------- 17.5/150.0 MB 6.9 MB/s eta 0:00:20
   ---- ----------------------------------- 18.0/150.0 MB 6.6 MB/s eta 0:00:20
   ---- ----------------------------------- 18.5/150.0 MB 6.4 MB/s eta 0:00:21
   ----- ---------------------------------- 18.9/150.0 MB 6.2 MB/s eta 0:00:22
   ----- ---------------------------------- 19.5/150.0 MB 6.0 MB/s eta 0:00:22
   ----- ---------------------------------- 20.0/150.0 MB 5.8 MB/s eta 0:00:23
   ----- ---------------------------------- 20.4/150.0 MB 5.8 MB/s eta 0:00:23
   ----- ---------------------------------- 20.9/150.0 MB 5.5 MB/s eta 0:00:24
   ----- ---------------------------------- 21.5/150.0 MB 5.4 MB/s eta 0:00:24
   ----- ---------------------------------- 22.0/150.0 MB 5.3 MB/s eta 0:00:25
   ------ --------------------------------- 22.7/150.0 MB 5.1 MB/s eta 0:00:25
   ------ --------------------------------- 23.4/150.0 MB 5.1 MB/s eta 0:00:25
   ------ --------------------------------- 24.4/150.0 MB 5.8 MB/s eta 0:00:22
   ------ --------------------------------- 25.2/150.0 MB 6.5 MB/s eta 0:00:20
   ------- -------------------------------- 26.5/150.0 MB 7.2 MB/s eta 0:00:18
   ------- -------------------------------- 27.8/150.0 MB 7.8 MB/s eta 0:00:16
   ------- -------------------------------- 29.4/150.0 MB 8.3 MB/s eta 0:00:15
   -------- ------------------------------- 30.8/150.0 MB 9.1 MB/s eta 0:00:14
   -------- ------------------------------- 30.9/150.0 MB 9.1 MB/s eta 0:00:14
   -------- ------------------------------- 32.5/150.0 MB 9.9 MB/s eta 0:00:12
   --------- ------------------------------ 33.8/150.0 MB 10.2 MB/s eta 0:00:12
   --------- ------------------------------ 35.3/150.0 MB 11.1 MB/s eta 0:00:11
   --------- ------------------------------ 36.7/150.0 MB 11.9 MB/s eta 0:00:10
   ---------- ----------------------------- 38.7/150.0 MB 13.1 MB/s eta 0:00:09
   ----------- ---------------------------- 41.6/150.0 MB 15.2 MB/s eta 0:00:08
   ----------- ---------------------------- 43.0/150.0 MB 16.8 MB/s eta 0:00:07
   ----------- ---------------------------- 44.2/150.0 MB 17.3 MB/s eta 0:00:07
   ------------ --------------------------- 45.3/150.0 MB 16.0 MB/s eta 0:00:07
   ------------ --------------------------- 46.8/150.0 MB 16.0 MB/s eta 0:00:07
   ------------ --------------------------- 47.3/150.0 MB 15.2 MB/s eta 0:00:07
   ------------ --------------------------- 48.6/150.0 MB 14.6 MB/s eta 0:00:07
   ------------- -------------------------- 50.2/150.0 MB 14.6 MB/s eta 0:00:07
   ------------- -------------------------- 51.7/150.0 MB 14.5 MB/s eta 0:00:07
   -------------- ------------------------- 53.0/150.0 MB 14.6 MB/s eta 0:00:07
   -------------- ------------------------- 54.7/150.0 MB 14.9 MB/s eta 0:00:07
   --------------- ------------------------ 56.6/150.0 MB 14.9 MB/s eta 0:00:07
   --------------- ------------------------ 58.1/150.0 MB 16.8 MB/s eta 0:00:06
   --------------- ------------------------ 58.6/150.0 MB 15.2 MB/s eta 0:00:07
   --------------- ------------------------ 59.6/150.0 MB 14.9 MB/s eta 0:00:07
   ---------------- ----------------------- 60.2/150.0 MB 13.9 MB/s eta 0:00:07
   ---------------- ----------------------- 60.7/150.0 MB 13.9 MB/s eta 0:00:07
   ---------------- ----------------------- 61.3/150.0 MB 13.1 MB/s eta 0:00:07
   ---------------- ----------------------- 61.9/150.0 MB 12.4 MB/s eta 0:00:08
   ---------------- ----------------------- 62.4/150.0 MB 12.1 MB/s eta 0:00:08
   ---------------- ----------------------- 62.9/150.0 MB 11.3 MB/s eta 0:00:08
   ---------------- ----------------------- 63.6/150.0 MB 10.7 MB/s eta 0:00:09
   ----------------- ---------------------- 64.2/150.0 MB 10.7 MB/s eta 0:00:08
   ----------------- ---------------------- 64.7/150.0 MB 10.2 MB/s eta 0:00:09
   ----------------- ---------------------- 65.2/150.0 MB 9.8 MB/s eta 0:00:09
   ----------------- ---------------------- 65.7/150.0 MB 9.1 MB/s eta 0:00:10
   ----------------- ---------------------- 66.3/150.0 MB 8.5 MB/s eta 0:00:10
   ----------------- ---------------------- 67.5/150.0 MB 8.2 MB/s eta 0:00:11
   ------------------ --------------------- 68.0/150.0 MB 8.0 MB/s eta 0:00:11
   ------------------ --------------------- 68.8/150.0 MB 8.2 MB/s eta 0:00:10
   ------------------ --------------------- 69.4/150.0 MB 8.2 MB/s eta 0:00:10
   ------------------ --------------------- 70.1/150.0 MB 8.4 MB/s eta 0:00:10
   ------------------ --------------------- 70.9/150.0 MB 8.3 MB/s eta 0:00:10
   ------------------- -------------------- 71.9/150.0 MB 8.7 MB/s eta 0:00:09
   ------------------- -------------------- 73.1/150.0 MB 9.1 MB/s eta 0:00:09
   ------------------- -------------------- 74.1/150.0 MB 9.5 MB/s eta 0:00:08
   -------------------- ------------------- 75.0/150.0 MB 10.1 MB/s eta 0:00:08
   -------------------- ------------------- 75.3/150.0 MB 9.9 MB/s eta 0:00:08
   -------------------- ------------------- 75.3/150.0 MB 9.9 MB/s eta 0:00:08
   -------------------- ------------------- 75.3/150.0 MB 9.9 MB/s eta 0:00:08
   -------------------- ------------------- 76.7/150.0 MB 10.7 MB/s eta 0:00:07
   -------------------- ------------------- 77.5/150.0 MB 10.2 MB/s eta 0:00:08
   --------------------- ------------------ 79.1/150.0 MB 11.5 MB/s eta 0:00:07
   --------------------- ------------------ 80.6/150.0 MB 12.1 MB/s eta 0:00:06
   --------------------- ------------------ 81.6/150.0 MB 12.4 MB/s eta 0:00:06
   ---------------------- ----------------- 82.9/150.0 MB 12.8 MB/s eta 0:00:06
   ---------------------- ----------------- 84.4/150.0 MB 13.6 MB/s eta 0:00:05
   ---------------------- ----------------- 86.1/150.0 MB 16.8 MB/s eta 0:00:04
   ----------------------- ---------------- 87.1/150.0 MB 18.2 MB/s eta 0:00:04
   ----------------------- ---------------- 88.4/150.0 MB 18.2 MB/s eta 0:00:04
   ----------------------- ---------------- 89.2/150.0 MB 16.4 MB/s eta 0:00:04
   ------------------------ --------------- 91.5/150.0 MB 16.8 MB/s eta 0:00:04
   ------------------------ --------------- 93.2/150.0 MB 16.8 MB/s eta 0:00:04
   ------------------------- -------------- 94.5/150.0 MB 16.4 MB/s eta 0:00:04
   ------------------------- -------------- 95.8/150.0 MB 16.8 MB/s eta 0:00:04
   ------------------------- -------------- 97.1/150.0 MB 17.3 MB/s eta 0:00:04
   -------------------------- ------------- 98.6/150.0 MB 17.7 MB/s eta 0:00:03
   -------------------------- ------------- 99.6/150.0 MB 17.7 MB/s eta 0:00:03
   -------------------------- ------------ 100.6/150.0 MB 17.7 MB/s eta 0:00:03
   -------------------------- ------------ 101.2/150.0 MB 16.8 MB/s eta 0:00:03
   -------------------------- ------------ 101.4/150.0 MB 14.9 MB/s eta 0:00:04
   -------------------------- ------------ 101.7/150.0 MB 13.9 MB/s eta 0:00:04
   -------------------------- ------------ 102.1/150.0 MB 13.6 MB/s eta 0:00:04
   -------------------------- ------------ 102.5/150.0 MB 13.1 MB/s eta 0:00:04
   -------------------------- ------------ 103.1/150.0 MB 12.1 MB/s eta 0:00:04
   -------------------------- ------------ 103.6/150.0 MB 11.7 MB/s eta 0:00:04
   --------------------------- ----------- 104.1/150.0 MB 11.5 MB/s eta 0:00:04
   --------------------------- ----------- 104.7/150.0 MB 11.3 MB/s eta 0:00:05
   --------------------------- ----------- 105.2/150.0 MB 11.1 MB/s eta 0:00:05
   --------------------------- ----------- 105.8/150.0 MB 10.9 MB/s eta 0:00:05
   --------------------------- ----------- 106.3/150.0 MB 10.6 MB/s eta 0:00:05
   --------------------------- ----------- 106.9/150.0 MB 10.2 MB/s eta 0:00:05
   --------------------------- ----------- 107.6/150.0 MB 10.1 MB/s eta 0:00:05
   ---------------------------- ----------- 108.1/150.0 MB 9.6 MB/s eta 0:00:05
   ----------------------------- ---------- 108.8/150.0 MB 9.4 MB/s eta 0:00:05
   ----------------------------- ---------- 109.4/150.0 MB 9.2 MB/s eta 0:00:05
   ----------------------------- ---------- 110.1/150.0 MB 9.4 MB/s eta 0:00:05
   ----------------------------- ---------- 110.8/150.0 MB 9.2 MB/s eta 0:00:05
   ----------------------------- ---------- 111.4/150.0 MB 9.5 MB/s eta 0:00:05
   ----------------------------- --------- 112.2/150.0 MB 10.6 MB/s eta 0:00:04
   ----------------------------- --------- 113.2/150.0 MB 11.5 MB/s eta 0:00:04
   ----------------------------- --------- 114.1/150.0 MB 12.4 MB/s eta 0:00:03
   ----------------------------- --------- 115.1/150.0 MB 13.1 MB/s eta 0:00:03
   ------------------------------ -------- 116.0/150.0 MB 13.1 MB/s eta 0:00:03
   ------------------------------ -------- 116.7/150.0 MB 13.4 MB/s eta 0:00:03
   ------------------------------ -------- 117.8/150.0 MB 14.2 MB/s eta 0:00:03
   ------------------------------ -------- 118.7/150.0 MB 15.2 MB/s eta 0:00:03
   ------------------------------- ------- 119.6/150.0 MB 15.6 MB/s eta 0:00:02
   ------------------------------- ------- 120.7/150.0 MB 16.4 MB/s eta 0:00:02
   ------------------------------- ------- 121.5/150.0 MB 16.0 MB/s eta 0:00:02
   ------------------------------- ------- 122.4/150.0 MB 16.8 MB/s eta 0:00:02
   -------------------------------- ------ 123.4/150.0 MB 16.4 MB/s eta 0:00:02
   -------------------------------- ------ 124.6/150.0 MB 16.0 MB/s eta 0:00:02
   -------------------------------- ------ 125.3/150.0 MB 15.6 MB/s eta 0:00:02
   -------------------------------- ------ 126.0/150.0 MB 15.2 MB/s eta 0:00:02
   -------------------------------- ------ 126.7/150.0 MB 15.2 MB/s eta 0:00:02
   --------------------------------- ----- 127.3/150.0 MB 14.9 MB/s eta 0:00:02
   --------------------------------- ----- 127.9/150.0 MB 13.9 MB/s eta 0:00:02
   --------------------------------- ----- 128.3/150.0 MB 13.4 MB/s eta 0:00:02
   --------------------------------- ----- 128.5/150.0 MB 12.6 MB/s eta 0:00:02
   --------------------------------- ----- 128.9/150.0 MB 12.4 MB/s eta 0:00:02
   --------------------------------- ----- 129.4/150.0 MB 12.1 MB/s eta 0:00:02
   --------------------------------- ----- 129.5/150.0 MB 12.1 MB/s eta 0:00:02
   --------------------------------- ----- 129.5/150.0 MB 12.1 MB/s eta 0:00:02
   --------------------------------- ----- 129.8/150.0 MB 10.7 MB/s eta 0:00:02
   ---------------------------------- ---- 131.7/150.0 MB 11.3 MB/s eta 0:00:02
   ---------------------------------- ---- 131.7/150.0 MB 11.5 MB/s eta 0:00:02
   ---------------------------------- ---- 131.7/150.0 MB 11.5 MB/s eta 0:00:02
   ---------------------------------- ---- 131.7/150.0 MB 11.5 MB/s eta 0:00:02
   ---------------------------------- ---- 131.7/150.0 MB 11.5 MB/s eta 0:00:02
   ---------------------------------- ---- 133.9/150.0 MB 10.6 MB/s eta 0:00:02
   ----------------------------------- --- 135.2/150.0 MB 10.6 MB/s eta 0:00:02
   ----------------------------------- --- 136.5/150.0 MB 10.9 MB/s eta 0:00:02
   ----------------------------------- --- 137.2/150.0 MB 10.4 MB/s eta 0:00:02
   ------------------------------------ --- 137.3/150.0 MB 9.8 MB/s eta 0:00:02
   ----------------------------------- --- 138.3/150.0 MB 10.1 MB/s eta 0:00:02
   ------------------------------------ -- 138.9/150.0 MB 10.1 MB/s eta 0:00:02
   ------------------------------------ -- 140.0/150.0 MB 11.9 MB/s eta 0:00:01
   ------------------------------------ -- 140.6/150.0 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ -- 141.4/150.0 MB 10.9 MB/s eta 0:00:01
   ------------------------------------ -- 142.1/150.0 MB 12.8 MB/s eta 0:00:01
   ------------------------------------- - 143.0/150.0 MB 12.1 MB/s eta 0:00:01
   ------------------------------------- - 143.9/150.0 MB 11.7 MB/s eta 0:00:01
   ------------------------------------- - 144.4/150.0 MB 11.5 MB/s eta 0:00:01
   ------------------------------------- - 144.9/150.0 MB 10.9 MB/s eta 0:00:01
   ------------------------------------- - 145.6/150.0 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------  146.4/150.0 MB 9.9 MB/s eta 0:00:01
   --------------------------------------  147.1/150.0 MB 10.2 MB/s eta 0:00:01
   --------------------------------------  148.1/150.0 MB 10.9 MB/s eta 0:00:01
   --------------------------------------  149.2/150.0 MB 11.9 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   --------------------------------------  150.0/150.0 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 150.0/150.0 MB 2.8 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.0.0

In [44]:
from xgboost import XGBClassifier

In [45]:
# Train the model
svc= SVC(kernel="sigmoid", gamma=1.0)
knc= KNeighborsClassifier()
mnb= MultinomialNB()
dtc=DecisionTreeClassifier(max_depth=5)
lrc=LogisticRegression(solver="liblinear",penalty="l1")
rfc=RandomForestClassifier(n_estimators=50, random_state=2)
abc=AdaBoostClassifier(n_estimators=50, random_state=2)
bc=BaggingClassifier(n_estimators=50, random_state=2)
etc=ExtraTreesClassifier(n_estimators=50, random_state=2)
gbct= GradientBoostingClassifier(n_estimators=50, random_state=2)
xgbc= XGBClassifier(n_estimator=50, random_state=2)

In [ ]:
clfs= {"svc":svc, "KNC":knc, "MNB":mnb, "DTC":dtc, "LRC":lrc, "RFC": rfc, "ABC":abc, "BC":bc, "ETC": etc, "GBC":gbtc,"XGBC":xgbc}

In [ ]:
#Model Evaluation
from sklearn.metrics import accuracy_score, precision_score
def train_classofier(clfs, x_train, y_train, x_test, y_test):
    clfs.fit(x_train, y_train)
    y_pred=clfs.predict(x_test)
    accuracy= accuracy_score(y_test, y_pred)
    precision= precision_score(y_test,y_pred)
    return accuracy, precision